"""reimbursement model

Revision ID: 460f56d521d9
Revises: 961ced54ce28
Create Date: 2022-05-06 12:56:19.383643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460f56d521d9'
down_revision = '961ced54ce28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reimbursement', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reimbursement', 'name')
    # ### end Alembic commands ###
