"""caigou info

Revision ID: 936df6513d79
Revises: 2870f4730ba9
Create Date: 2022-05-12 20:07:13.785048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936df6513d79'
down_revision = '2870f4730ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reimbursement', sa.Column('billed', sa.Boolean(), nullable=True))
    op.add_column('reimbursement', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('reimbursement', sa.Column('send', sa.String(length=6), nullable=True))
    op.add_column('reimbursement', sa.Column('type', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_reimbursement_date'), 'reimbursement', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reimbursement_date'), table_name='reimbursement')
    op.drop_column('reimbursement', 'type')
    op.drop_column('reimbursement', 'send')
    op.drop_column('reimbursement', 'date')
    op.drop_column('reimbursement', 'billed')
    # ### end Alembic commands ###
