"""reimbusement model

Revision ID: 961ced54ce28
Revises: d4d2e75ddec0
Create Date: 2022-05-06 08:54:43.859514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961ced54ce28'
down_revision = 'd4d2e75ddec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reimbursement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reimbursement_timestamp'), 'reimbursement', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reimbursement_timestamp'), table_name='reimbursement')
    op.drop_table('reimbursement')
    # ### end Alembic commands ###
