"""empty message

Revision ID: 96204ffe70d8
Revises: 59ad47277e08
Create Date: 2021-04-17 10:12:57.430264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96204ffe70d8'
down_revision = '59ad47277e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo')
    # ### end Alembic commands ###
