jijin=[["000009","HXCZHH","华夏成长混合","混合型","HUAXIACHENGZHANGHUNHE"],
       ["000010","HXCZHH","华夏成长混合(后端)","混合型","HUAXIACHENGZHANGHUNHE"],
       ["000013","ZHKZZZQA","中海可转债债券A","债券型","ZHONGHAIKEZHUANZHAIZHAIQUANA"]]