pipeline_name: classifier
pipeline_nodes:
- src0:
    next: decode0
    type: Source
- decode0:
    next: predict0
    type: Decode
- predict0:
    init_params:
      gpu_id: 0
      model_dir: D:\work\PaddleX_Workspace\cat_dog_export_model\inference_model\inference_model
      use_gpu: false
      use_trt: false
    next: sink0
    type: Predict
- sink0:
    type: Sink
version: 1.0.0
